workflows:
  ios-firebase-dist:
    name: iOS to Firebase Distribution
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      vars:
        BUNDLE_ID: "com.miwken.habittracker"
      groups:
        - firebase_credentials # позже добавим
    scripts:
      - name: Setup Flutter
        script: |
          flutter --version
          flutter pub get
      - name: Build iOS
        script: |
          flutter build ios --release --no-codesign
      - name: Package IPA
        script: |
          cd ios
          xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Debug \
            -allowProvisioningUpdates \
            -archivePath /tmp/Runner.xcarchive \
            archive
          
          # Создаем IPA без подписи (для теста)
          mkdir -p Payload
          cp -r /tmp/Runner.xcarchive/Products/Applications/Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - ios/Runner.ipa